# Generated by Django 2.1.1 on 2018-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test1Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr_ci', models.CharField(max_length=50)),
                ('chr_start', models.IntegerField()),
                ('chr_end', models.IntegerField()),
            ],
            options={
                'db_table': 'test1_chromosome',
            },
        ),
    ]
