# Generated by Django 2.2.3 on 2019-07-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chromosome_length',
            fields=[
                ('chr_id', models.AutoField(primary_key=True, serialize=False)),
                ('assembly', models.CharField(max_length=100)),
                ('chr_num', models.CharField(max_length=50)),
                ('chr_length', models.IntegerField()),
            ],
            options={
                'db_table': 'chromosome_length',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='danRer11_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'danRer11_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='danRer11_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'danRer11_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='danRer11_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'danRer11_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='danRer11_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'danRer11_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='hg19_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'hg19_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='hg19_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'hg19_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='hg19_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'hg19_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='hg19_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'hg19_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='hg38_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'hg38_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='hg38_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'hg38_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='hg38_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'hg38_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='hg38_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'hg38_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='mm10_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'mm10_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='mm10_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'mm10_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='mm10_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'mm10_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='mm10_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'mm10_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='rn6_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'rn6_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='rn6_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'rn6_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='rn6_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'rn6_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='rn6_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'rn6_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='sacCer3_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'sacCer3_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='sacCer3_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'sacCer3_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='sacCer3_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'sacCer3_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='sacCer3_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'sacCer3_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
    ]
