# Generated by Django 2.1.4 on 2019-06-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chromosome_length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.CharField(max_length=100)),
                ('chr_num', models.CharField(max_length=50)),
                ('chr_length', models.IntegerField()),
            ],
            options={
                'db_table': 'tools_chromosome_length',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToolsAnnotation',
            fields=[
                ('gene_type', models.CharField(max_length=50)),
                ('gene_name', models.CharField(max_length=200)),
                ('chr_ci', models.CharField(max_length=50)),
                ('gene_start', models.IntegerField()),
                ('gene_end', models.IntegerField()),
                ('gene_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tools_annotation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToolsScalegenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('chr_ci', models.CharField(max_length=30)),
                ('gene_min_start', models.IntegerField()),
                ('gene_max_end', models.IntegerField()),
                ('genelens_wiki', models.IntegerField()),
            ],
            options={
                'db_table': 'tools_scalegenome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='species_circRNAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=255)),
                ('transcript', models.CharField(max_length=255)),
                ('chr_num', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('components', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='species_genome_exons_introns',
            fields=[
                ('gene', models.CharField(max_length=255)),
                ('transcript', models.CharField(max_length=255)),
                ('exin_type', models.CharField(max_length=255)),
                ('chr_num', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=2)),
                ('id_en', models.CharField(db_column='id', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('modifications', models.TextField()),
                ('id_notuse', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='species_genome_genes',
            fields=[
                ('chr_num', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=2)),
                ('id_en', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gene_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='species_genome_transcripts',
            fields=[
                ('gene', models.CharField(max_length=255)),
                ('chr_num', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(max_length=2)),
                ('id_en', models.CharField(db_column='id', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsChromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr_ci', models.CharField(max_length=50)),
                ('chr_start', models.IntegerField()),
                ('chr_end', models.IntegerField()),
                ('max_length_circ', models.IntegerField()),
                ('min_length_circ', models.IntegerField()),
            ],
            options={
                'db_table': 'tools_chromosome',
            },
        ),
        migrations.CreateModel(
            name='UploadParametersMD5',
            fields=[
                ('md5', models.CharField(db_column='MD5', max_length=32, primary_key=True, serialize=False)),
                ('status', models.IntegerField(db_column='Status')),
                ('file_type', models.CharField(db_column='FileType', max_length=100)),
                ('path', models.CharField(db_column='path', max_length=200)),
                ('species', models.CharField(db_column='Species', max_length=255)),
                ('time', models.FloatField(db_column='time_created')),
            ],
            options={
                'db_table': 'tools_uploadmd5',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('md5', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id_gene', models.CharField(db_column='id', max_length=255)),
                ('chr_num', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('gene_type', models.CharField(max_length=100)),
                ('circ_on_gene_all', models.TextField()),
            ],
            options={
                'db_table': 'tools_usertable',
            },
        ),
        migrations.CreateModel(
            name='danRer11_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'danRer11_species_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='danRer11_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'danRer11_species_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='danRer11_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'danRer11_species_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='danRer11_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'danRer11_species_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='hg19_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'hg19_species_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='hg19_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'hg19_species_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='hg19_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'hg19_species_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='hg19_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'hg19_species_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='hg38_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'hg38_species_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='hg38_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'hg38_species_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='hg38_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'hg38_species_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='hg38_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'hg38_species_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='mm10_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'mm10_species_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='mm10_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'mm10_species_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='mm10_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'mm10_species_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='mm10_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'mm10_species_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='rn6_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'rn6_species_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='rn6_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'rn6_species_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='rn6_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'rn6_species_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='rn6_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'rn6_species_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.CreateModel(
            name='sacCer3_species_circRNAs',
            fields=[
                ('species_circrnas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_circRNAs')),
            ],
            options={
                'db_table': 'sacCer3_species_circRNAs',
                'managed': False,
            },
            bases=('tools.species_circrnas',),
        ),
        migrations.CreateModel(
            name='sacCer3_species_genome_exons_introns',
            fields=[
                ('species_genome_exons_introns_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_exons_introns')),
            ],
            options={
                'db_table': 'sacCer3_species_genome_exons_introns',
                'managed': False,
            },
            bases=('tools.species_genome_exons_introns',),
        ),
        migrations.CreateModel(
            name='sacCer3_species_genome_genes',
            fields=[
                ('species_genome_genes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_genes')),
            ],
            options={
                'db_table': 'sacCer3_species_genome_genes',
                'managed': False,
            },
            bases=('tools.species_genome_genes',),
        ),
        migrations.CreateModel(
            name='sacCer3_species_genome_transcripts',
            fields=[
                ('species_genome_transcripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools.species_genome_transcripts')),
            ],
            options={
                'db_table': 'sacCer3_species_genome_transcripts',
                'managed': False,
            },
            bases=('tools.species_genome_transcripts',),
        ),
        migrations.AddField(
            model_name='toolschromosome',
            name='caseid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.UploadParametersMD5'),
        ),
    ]
