# Generated by Django 2.1.1 on 2018-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsScalegenome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('chr_ci', models.CharField(max_length=30)),
                ('gene_min_start', models.IntegerField()),
                ('gene_max_end', models.IntegerField()),
            ],
            options={
                'db_table': 'tools_scalegenome',
                'managed': False,
            },
        ),
    ]
