# Generated by Django 2.1 on 2018-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciridata',
            name='rawfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
