# Generated by Django 2.1 on 2018-08-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_ciridata_rawfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='eachObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circRNA_ID', models.CharField(max_length=100)),
                ('chr_ci', models.CharField(max_length=40)),
                ('circRNA_start', models.IntegerField()),
                ('circRNA_end', models.IntegerField()),
                ('junction_reads', models.IntegerField()),
                ('non_junction_reads', models.IntegerField()),
                ('circRNA_type', models.CharField(max_length=100)),
                ('gene_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ciridata',
            name='chr_ci',
        ),
        migrations.RemoveField(
            model_name='ciridata',
            name='circRNA_ID',
        ),
        migrations.RemoveField(
            model_name='ciridata',
            name='circRNA_end',
        ),
        migrations.RemoveField(
            model_name='ciridata',
            name='circRNA_start',
        ),
        migrations.RemoveField(
            model_name='ciridata',
            name='circRNA_type',
        ),
        migrations.RemoveField(
            model_name='ciridata',
            name='gene_id',
        ),
        migrations.RemoveField(
            model_name='ciridata',
            name='junction_reads',
        ),
        migrations.RemoveField(
            model_name='ciridata',
            name='non_junction_reads',
        ),
    ]
