# Generated by Django 2.1 on 2018-09-10 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180811_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploadCase',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filetype', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CIRIdata',
        ),
        migrations.RemoveField(
            model_name='eachobservation',
            name='id',
        ),
        migrations.AlterField(
            model_name='eachobservation',
            name='circRNA_ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='eachobservation',
            name='caseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.uploadCase'),
        ),
    ]
