# Generated by Django 2.1 on 2018-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180910_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcase',
            name='filetype',
        ),
        migrations.AddField(
            model_name='eachobservation',
            name='SM_MS_SMS',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='eachobservation',
            name='junction_reads_ID',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eachobservation',
            name='junction_reads_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eachobservation',
            name='strand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eachobservation',
            name='chr_ci',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eachobservation',
            name='circRNA_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eachobservation',
            name='circRNA_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eachobservation',
            name='circRNA_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eachobservation',
            name='gene_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eachobservation',
            name='junction_reads',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eachobservation',
            name='non_junction_reads',
            field=models.IntegerField(null=True),
        ),
    ]
