# Generated by Django 2.1 on 2018-09-07 02:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eachObservation',
            fields=[
                ('circRNA_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('chr_ci', models.CharField(max_length=40)),
                ('circRNA_start', models.IntegerField()),
                ('circRNA_end', models.IntegerField()),
                ('junction_reads', models.IntegerField()),
                ('non_junction_reads', models.IntegerField()),
                ('circRNA_type', models.CharField(max_length=100)),
                ('gene_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='uploadCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filetype', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='eachobservation',
            name='caseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.uploadCase'),
        ),
    ]
