version: '3'

services:
  db:
    image: mysql:8.0
    expose:
        - 3307
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'circDraw'
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_USER: 'root'

  web:
    container_name: uwsgi_django_container
    build: .
    restart: always
    command: uwsgi -i docker/uwsgi_conf/uwsgi.ini
    volumes:
      - .:/docker_api
    depends_on:
      - db
    links:
      - db

  nginx:
    container_name: nginx-container
    restart: always
    depends_on:
      - web
    build: docker/nginx
    ports:
      - 8888:80
    volumes:
      - .:/docker_api
    

