version: '3'

services:
  db:
    image: mysql:8.0
    expose:
        - 3306
    environment:
      MYSQL_DATABASE: 'circDraw'
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_USER: 'root'

  web:
    container_name: web-container
    build: .
    restart: always
    command: uwsgi -i ./uwsgi_conf/uwsgi.ini
    volumes:
      - .:/docker_api
    expose:
      - 8888
    depends_on:
      - db
    links:
        - db:mysql

  nginx:
    container_name: nginx-container
    restart: always
    depends_on:
      - web
    build: ./nginx
    environment:
       - "affinity:container==*web-container*"
    ports:
      - 80:80
    volumes:
      - .:/docker_api
    

